#!/usr/bin/env node
/**
 * Codegen: Pydantic AnalysisResponse → Zod schema
 *
 * Steps:
 *   1. Run `python scripts/export_openapi.py` to write openapi.json
 *   2. Read openapi.json and convert to Zod code
 *   3. Write packages/api-client/src/generated.ts
 *
 * Run:       node scripts/codegen.mjs
 * CI check:  node scripts/codegen.mjs --check  (exits 1 if generated.ts is stale)
 */

import { spawnSync } from "node:child_process";
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const SCHEMA_PATH = resolve(ROOT, "openapi.json");
const OUT_PATH = resolve(ROOT, "packages/api-client/src/generated.ts");
const CHECK_MODE = process.argv.includes("--check");

// ── 1. Export JSON Schema from Pydantic (uv run — no full venv needed) ───

console.log("Exporting AnalysisResponse JSON Schema...");
const mlApiDir = resolve(ROOT, "apps/ml-api");
const result = spawnSync(
  "uv",
  ["run", "--no-project", "--with", "pydantic", "python", "scripts/export_openapi.py", "--out", SCHEMA_PATH],
  {
    cwd: mlApiDir,
    stdio: "inherit",
    env: { ...process.env, PYTHONPATH: mlApiDir },
  }
);
if (result.status !== 0) {
  process.stderr.write("ERROR: export_openapi.py failed\n");
  process.exit(1);
}

// ── 2. Convert JSON Schema → Zod code ────────────────────────────────────

const schema = JSON.parse(readFileSync(SCHEMA_PATH, "utf8"));
const props = schema.properties;
const required = new Set(schema.required ?? []);

function resolveType(prop) {
  // anyOf with null → nullable
  if (prop.anyOf) {
    const nonNull = prop.anyOf.filter((s) => s.type !== "null");
    if (nonNull.length === 1) {
      return `${resolveType(nonNull[0])}.nullable()`;
    }
    return "z.unknown()";
  }

  if (prop.enum) {
    const vals = prop.enum.map((v) => JSON.stringify(v)).join(", ");
    return `z.enum([${vals}])`;
  }

  if (prop.type === "array") {
    const itemType = prop.items ? resolveType(prop.items) : "z.unknown()";
    const base = `z.array(${itemType})`;
    return prop.default !== undefined ? `${base}.default(${JSON.stringify(prop.default)})` : base;
  }

  if (prop.type === "object" && prop.additionalProperties) {
    return `z.record(${resolveType(prop.additionalProperties)})`;
  }

  if (prop.type === "integer") {
    let z = "z.number().int()";
    if (prop.minimum !== undefined) z += `.min(${prop.minimum})`;
    if (prop.maximum !== undefined) z += `.max(${prop.maximum})`;
    return z;
  }

  if (prop.type === "number") {
    let z = "z.number()";
    if (prop.minimum !== undefined) z += `.min(${prop.minimum})`;
    if (prop.maximum !== undefined) z += `.max(${prop.maximum})`;
    return z;
  }

  if (prop.type === "string") return "z.string()";
  if (prop.type === "boolean") return "z.boolean()";
  if (prop.type === "null") return "z.null()";
  return "z.unknown()";
}

function propToZod(name, prop) {
  let z = resolveType(prop);
  if (!required.has(name)) {
    if (prop.default === null) {
      // Pydantic `= None` fields: nullable already applied, add optional so
      // the key can be absent entirely (not just null).
      z += ".optional()";
    } else if (prop.default === undefined) {
      // Non-required arrays without explicit default → .default([]) mirrors
      // Pydantic's default_factory=list (not serialised to JSON Schema).
      const isArray = prop.type === "array" || prop.items !== undefined;
      z += isArray ? ".default([])" : ".optional()";
    }
    // prop.default is a concrete non-null value — resolveType already emits .default()
  }
  return z;
}

const fieldLines = Object.entries(props)
  .map(([name, prop]) => `  ${name}: ${propToZod(name, prop)},`)
  .join("\n");

const generated =
  `// DO NOT EDIT — auto-generated by scripts/codegen.mjs\n` +
  `// Source: apps/ml-api/app/schemas/analysis.py (AnalysisResponse)\n` +
  `// Regenerate: node scripts/codegen.mjs\n\n` +
  `import { z } from "zod";\n\n` +
  `export const AnalysisResponseSchema = z.object({\n` +
  `${fieldLines}\n` +
  `});\n\n` +
  `export type AnalysisResponse = z.infer<typeof AnalysisResponseSchema>;\n\n` +
  `export async function parseAnalysisResponse(data: unknown): Promise<AnalysisResponse> {\n` +
  `  return AnalysisResponseSchema.parse(data);\n` +
  `}\n`;

// ── 3. Write or check ─────────────────────────────────────────────────────

if (CHECK_MODE) {
  if (!existsSync(OUT_PATH)) {
    process.stderr.write("ERROR: packages/api-client/src/generated.ts does not exist.\nRun: node scripts/codegen.mjs\n");
    process.exit(1);
  }
  const existing = readFileSync(OUT_PATH, "utf8");
  // Strip header (timestamps/paths vary) before comparing
  const stripHeader = (s) => s.replace(/^(\/\/[^\n]*\n){3}\n/, "");
  if (stripHeader(existing) !== stripHeader(generated)) {
    process.stderr.write("ERROR: packages/api-client/src/generated.ts is stale.\nRun: node scripts/codegen.mjs\n");
    process.exit(1);
  }
  console.log("✓ packages/api-client/src/generated.ts is up to date.");
} else {
  writeFileSync(OUT_PATH, generated, "utf8");
  console.log(`✓ Written ${OUT_PATH}`);
}
